name: BuildFFA
authors: [Thorsten, Luca, Lara]
version: 1.0.0
main: ch.luca.hydroslide.buildffa.BuildFFA
api-version: 1.19
depend:
  - ProtocolLib
commands:
  build:
  setup:
  inventory:
    aliases: [inv, inventar, sortieren, invs]
  ranking:
    aliases: [top, top10, ranks]
  stats:
  vanish:
    aliases: [v]
  teleport:
    aliases: [tp]


